print("========= DESAFIO 01 =========")
nome = input("Qual é o seu nome?")
print('========================')
print('\n Olá, ', nome, ' seja bem vindo, prazer em te conhecer' )
print('\n ========= DESAFIO 02 =========')
dia = input('Dia = ')
mes = input('Mês = ')
ano = input('Ano = ')
print('\n Você nasceu ' + dia + ' de ' + mes + ' de ' + ano+ ', correto?')
print('\n ======== DESAFIO 03 ========')
numero01 = int(input('Qual o numero? '))
numero02 = int(input('Qual o segundo numero? '))

print('A soma dos numeros é ' , numero01 + numero02)